# -----------------------------------------------------------------------------
# csi-config-secret.yaml 
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: csi-config-secret
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "<CLUSTER_NAMESPACE>/<CLUSTER_NAME>"
    user = "administrator@vsphere.local"
    password = "password"
    port = 443
    [VirtualCenter "vcenter.local"]
    datacenters = "datacenter-name"
    insecure-flag = true # use for selfsigned certificates

